# Railway Deployment Configuration

# Use nixpacks providers for Node.js and .NET
[providers]
node = "20"
dotnet = "9.0"

[phases.setup]
nixPkgs = ["nodejs", "npm", "dotnet-sdk_9"]

[phases.build]
cmds = [
    "cd frontend && npm ci --include=dev",
    "cd frontend && npm run build", 
    "cd .. && dotnet restore MyWebsite/MyWebsite.csproj",
    "dotnet publish MyWebsite/MyWebsite.csproj -c Release -o out"
]

[phases.start]
cmd = "cd out && dotnet MyWebsite.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"
